<?xml version="1.0" encoding="utf-8"?><Database Name="empresa" Class="DataEmpresaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=empresa;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="empresaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.area" Member="area">
    <Type Name="area">
      <Column Name="are_cod" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="are_des" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="area_empleado" Member="empleado" ThisKey="are_cod" OtherKey="are_cod" Type="empleado" />
    </Type>
  </Table>
  <Table Name="dbo.empleado" Member="empleado">
    <Type Name="empleado">
      <Column Name="emp_cod" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="emp_nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="are_cod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="area_empleado" Member="area" ThisKey="are_cod" OtherKey="are_cod" Type="area" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Actualiza_Area" Method="SP_Actualiza_Area">
    <Parameter Name="codigo2" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcion2" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Buscar_Area" Method="SP_Buscar_Area">
    <Parameter Name="codigo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Buscar_AreaResult">
      <Column Name="are_cod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="are_des" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Eliminar_Area" Method="SP_Eliminar_Area">
    <Parameter Name="codigo3" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Insertar_Area" Method="SP_Insertar_Area">
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Listar_Area" Method="SP_Listar_Area">
    <ElementType Name="SP_Listar_AreaResult">
      <Column Name="are_cod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="are_des" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>